Repository octopusden/octopus-jira-utils, pull requests merged in 2023-09, with the labels that each got.

#2 build was made buildable
  components-registry/pom.xml
  helper-services/pom.xml
  pom.xml
Labels: bug

#3 javadoc set up
  pom.xml
Labels: bug, documentation

#4 Disable javadoc for components-registry, which is kotlin project
  components-registry/pom.xml
Labels: bug, documentation

#5 Generate doc bundle for kotlin by dokka
  components-registry/pom.xml
Labels: bug, documentation

#6 OCTOPUS-497 Bump CRS version from 2.0.10 to 2.0.11
  components-registry/pom.xml
  components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryService.kt
  components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
Labels: enhancement

#7 Add logging of query for JiraSearchServiceImpl#checkMessageSet
  helper-services/src/main/java/org/octopusden/octopus/jira/utils/impl/JiraSearchServiceImpl.java
Labels: enhancement

#8 Log jql query if JiraSearchServiceImpl.checkMessageSet finds problems
  helper-services/src/main/java/org/octopusden/octopus/jira/utils/impl/JiraSearchServiceImpl.java
Labels: bug
